server:
  port: 9104

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    registerWithEureka: true
    # 是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/
spring:
  application:
    name: provider
  profiles: provider1

name: provider1

---
server:
  port: 9105

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    registerWithEureka: true
    # 是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/
spring:
  application:
    name: provider
  profiles: provider2

name: provider2