server:
  port: 9006

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    registerWithEureka: true
    # 是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/
spring:
  application:
    name: consumer
feign:
  hystrix:
    enabled: true
