server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 是否将自己注册到Eureka Server，默认为true
    registerWithEureka: false
    # 是否从Eureka Server获取注册信息，默认为true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server-8761
