spring:
  application:
    name: eureka-server
  profiles: peer1
server:
  port: 9101
eureka:
  instance:
    hostname: peer1
    # 使用IP注册到其他节点时需设置此参数为true
#    prefer-ip-address: true
  client:
#    # 是否将自己注册到Eureka Server，默认为true
#    registerWithEureka: false
#    # 是否从Eureka Server获取注册信息，默认为true
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:9102/eureka/,http://peer3:9103/eureka/
---
spring:
  application:
    name: eureka-server
  profiles: peer2
server:
  port: 9102
eureka:
  instance:
    hostname: peer2
#    prefer-ip-address: true
  client:
    #    # 是否将自己注册到Eureka Server，默认为true
    #    registerWithEureka: false
    #    # 是否从Eureka Server获取注册信息，默认为true
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer3:9103/eureka/
---
spring:
  application:
    name: eureka-server
  profiles: peer3
server:
  port: 9103
eureka:
  instance:
    hostname: peer3
#    prefer-ip-address: true
  client:
    #    # 是否将自己注册到Eureka Server，默认为true
    #    registerWithEureka: false
    #    # 是否从Eureka Server获取注册信息，默认为true
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:9101/eureka/,http://peer2:9102/eureka/
